openapi: 3.0.1
info:
  title: My Service
  description: This is my cool service!
  x-cortex-tag: my-service
  x-cortex-type: service
  x-cortex-git:
    github:
      repository: cortex/docs
      basepath: myService
      alias: log_parser
